main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: /publication/
    weight: 20
  - name: Projects
    url: /project/
    weight: 30
  - name: Talks
    url: /talk/
    weight: 40
  - name: Blog
    url: /post/
    weight: 50
  - name: CV
    url: /uploads/cv.pdf
    weight: 60
  - name: Contact
    url: /#contact
    weight: 70
