# ── 基本信息（会作为站点默认作者显示）
author: "白健行"
role: "伦理学博士｜康德哲学｜跨文化伦理"
organization: "山东大学哲学与社会发展学院（伦理学）"
superuser: true

# 站点描述（用于 SEO）
description: "康德伦理共同体、世界公民与好客伦理；跨文化诠释学；哲学人类学与政治哲学研究。"

# 联系方式 & 社交（按需增删）
email: "you@example.com"
social:
  - icon: google-scholar
    icon_pack: ai
    link: "https://scholar.google.com/"
  - icon: orcid
    icon_pack: ai
    link: "https://orcid.org/0000-0002-XXXX-YYYY"
  - icon: github
    icon_pack: fab
    link: "https://github.com/baijianxing"
  - icon: linkedin
    icon_pack: fab
    link: "https://www.linkedin.com/in/你的英文用户名/"
  - icon: envelope
    icon_pack: fas
    link: "mailto:you@example.com"

# 主题/外观（可按喜好改）
theme: minimal
day_night: true
font: minimal

# 文章摘要长度
reading_time: true
show_date: true

# 默认封面图（可留空；或放置 /static/uploads/cover.jpg）
# images:
#   - "/uploads/cover.jpg"

# 数学/代码高亮（如不需要可设为 false）
math: false
diagram: false
highlight:
  style: github

# 评论/统计（按需启用）
# comments:
#   provider: giscus
#   giscus:
#     repo: "baijianxing/your-repo"
# analytics:
#   provider: plausible
#   plausible:
#     domain: "baijianxing.com"iiiiii k k k k k k k k k k k k k k k k k k k k k k k k k k 7
